# Generated by Django 5.2.3 on 2025-06-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To do'), ('wip', 'Wip'), ('on_hold', 'On hold'), ('done', 'Done')], default='to_do', max_length=50),
        ),
    ]
