# Generated by Django 5.1.6 on 2025-06-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='focused',
            field=models.BooleanField(default=False),
        ),
    ]
