# Generated by Django 5.1.6 on 2025-06-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0006_task_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
