# Generated by Django 5.1.6 on 2025-07-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0008_alter_task_options_alter_task_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='focused',
        ),
    ]
